<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #f0f0f0;
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
            font-weight: bold;
        }
        td {
            padding: 8px;
            border: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        .summary {
            margin-top: 20px;
            padding: 15px;
            background-color: #f0f0f0;
            border-radius: 5px;
        }
        .summary-item {
            margin: 5px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        @if($userName)
            <p><strong>User:</strong> {{ $userName }}</p>
        @endif
        @if($dateRange)
            <p><strong>Date Range:</strong> {{ $dateRange }}</p>
        @endif
        <p><strong>Generated:</strong> {{ $generatedAt }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                @if($isSystemWide)
                    <th>User</th>
                @endif
                <th>Date</th>
                <th>Description</th>
                <th>USD</th>
                <th>SYP</th>
                <th>TRY</th>
                <th>Invoice</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($expenses as $expense)
                <tr>
                    <td>{{ $expense->id }}</td>
                    @if($isSystemWide)
                        <td>{{ $expense->user->name ?? 'N/A' }}</td>
                    @endif
                    <td>{{ $expense->expense_date }}</td>
                    <td>{{ $expense->description }}</td>
                    <td>${{ number_format($expense->price_usd, 2) }}</td>
                    <td>{{ $expense->price_syp ? number_format($expense->price_syp, 2) : 'N/A' }}</td>
                    <td>{{ $expense->price_try ? number_format($expense->price_try, 2) : 'N/A' }}</td>
                    <td>{{ $expense->has_invoice ? 'Yes' : 'No' }}</td>
                    <td>{{ ucfirst($expense->sync_status) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="{{ $isSystemWide ? 9 : 8 }}" style="text-align: center;">No expenses found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    @if($expenses->isNotEmpty())
        <div class="summary">
            <h3>Summary</h3>
            <div class="summary-item">
                <strong>Total Expenses:</strong> {{ $expenses->count() }}
            </div>
            <div class="summary-item">
                <strong>Total USD:</strong> ${{ number_format($expenses->sum('price_usd'), 2) }}
            </div>
            @if($expenses->whereNotNull('price_syp')->count() > 0)
                <div class="summary-item">
                    <strong>Total SYP:</strong> {{ number_format($expenses->sum('price_syp'), 2) }}
                </div>
            @endif
            @if($expenses->whereNotNull('price_try')->count() > 0)
                <div class="summary-item">
                    <strong>Total TRY:</strong> {{ number_format($expenses->sum('price_try'), 2) }}
                </div>
            @endif
        </div>
    @endif

    <div class="footer">
        <p>This report was automatically generated by the Finance Management System</p>
    </div>
</body>
</html>
